name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,15 * *' # JST 9:00 on 1st and 15th every month

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ctest_unit:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-24.04

    env:
      MPIRUN: "mpiexec --oversubscribe -np 1"
      OMP_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v4

      - name: bootstrap and build
        uses: ./.github/actions/bootstrap-build
        with:
          build-dir: ${{ runner.workspace }}/build
          source-dir: ${{ github.workspace }}

      - name: ctest unit
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -L unit

  ctest_smoke:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            mpisize: 1
            ompsize: 1
          - os: ubuntu-24.04
            mpisize: 1
            ompsize: 3
          - os: macos-latest
            mpisize: 1
            ompsize: 1
      fail-fast: false

    env:
      MPIRUN: "mpiexec --oversubscribe -np ${{ matrix.mpisize }}"
      OMP_NUM_THREADS: ${{ matrix.ompsize }}

    steps:
      - uses: actions/checkout@v4

      - name: bootstrap and build
        uses: ./.github/actions/bootstrap-build
        with:
          build-dir: ${{ runner.workspace }}/build
          source-dir: ${{ github.workspace }}

      - name: ctest smoke
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -L smoke

  ctest_full_schedule:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        mpisize: [1, 3, 4, 9, 16]
        ompsize: [1]
        include:
          - os: ubuntu-24.04
            mpisize: 1
            ompsize: 3
          - os: macos-latest
            mpisize: 1
            ompsize: 1
      fail-fast: false

    env:
      MPIRUN: "mpiexec --oversubscribe -np ${{ matrix.mpisize }}"
      OMP_NUM_THREADS: ${{ matrix.ompsize }}

    steps:
      - uses: actions/checkout@v4

      - name: bootstrap and build
        uses: ./.github/actions/bootstrap-build
        with:
          build-dir: ${{ runner.workspace }}/build
          source-dir: ${{ github.workspace }}

      - name: ctest full (schedule, mpisize=1)
        if: ${{ matrix.mpisize == 1 }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V

      - name: ctest full-partition spinone (schedule, mpisize=3/9)
        if: ${{ matrix.mpisize == 3 || matrix.mpisize == 9 }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -R spinone

      - name: ctest full-partition non-spinone (schedule, mpisize=4/16)
        if: ${{ matrix.mpisize == 4 || matrix.mpisize == 16 }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -E spinone
